---
title: "Temario y cronograma"
---


## 1) Flujos de trabajo y análisis (0.5 días)
– Organización de proyectos y archivos (R Console & RStudio)
– Buenas prácticas para nombrar archivos y objetos
– Trabajando con rutas 
– Estructuras de datos
– Exploración rápida de datos

## Manipulación y limpieza de datos (1.5 días)
– Pasos a seguir para importar y reestructurar tablas y archivos.
– Principios de datos ordenados (tidy data) y herramientas del ‘tidyverse’ para ordenar datos
– Expresiones regulares para trabajar con cadenas de texto
– Herramientas para trabajar con datos faltantes 
– Formas de identificar Información repetida

Ejemplo completo de todos estos pasos con: 
	a) datos de presencia de especies obtenidos de GBIF 
	b) datos desordenados de trabajo de campo, estudio de caso con vegetación y con vertebrados  

## 3) Visualización de Datos (1 día)
– Introducción a ggplot2 (Gramática de gráficos)
– Representaciones gráficas de información
– Personalización de elementos gráficos (ejes, colores, fuentes, leyendas)
– Preparación de figuras científicas
	* Ejemplo de figuras complejas mostrando todos los resultados asociados a un análisis de componentes principales (PCA)
	* Combinación de figuras sin usar otro software, paquete ‘patchwork’
– Herramientas para exportar gráficos de alta resolución en múltiples formatos

## 4) Lo que nadie nos enseñó sobre R (1 día)
– Entornos de trabajo y configuración
– Iteración y vectorización para evitar repetición
– Trabajando con listas
– Manejo de matrices 
	* Aplicando manejo de matrices a datos de ecología de comunidades 
	* Matrices de correlación entre rasgos para estudios morfométricos
– Atajos y herramientas para mayor eficiencia
– Significado de los errores más comunes

## 5) Aspectos de geografía de la biodiversidad (1 día)
– Puntos, polígonos, rasters: nuevas paqueterías para manejo de datos espaciales 
* Calculando riqueza de especies para diferentes unidades espaciales 
– Paquetes para generar mapas bivariados 
– Trabajo con modelos de elevación digital 
– Filogenias: manejo y visualización 
